### PR TITLE
Regenerate civix and add postInstall

### PR DESCRIPTION
**Pull request by mattwire**
- postInstall is required otherwise the upgrader steps run on install.
- Regenerate civix to match current standard.
- Remove return from void functions.

### CODE REVIEW

**Comment by lucky091588** [comment]
Thank you @mattwire. I will check this and get back to you.

**Comment by twomice** [comment]
@mattwire When you say "Regenerate civix" (in this ticket title), do you mean `civix generate:module` or `civix generate:upgrader`? (I"m curious because I believe we have other extensions that will need the same treatment.)

**Comment by mattwire** [comment]
Yes. I do both as a matter of course as I believe it's completely safe to do so (obviously if you do not have an upgrader you do not need to regenerate that bit).

Also, if the extension is older check that hook_civicrm_postInstall is defined in the main extension.php file otherwise upgrader will run through all upgrade steps on install as well (postInstall hook sets the schema version in the DB).

**Comment by twomice** [comment]
Thanks @mattwire !

**Pull request merged**
